@hostname = localhost
@port = 3693
@host = {{hostname}}:{{port}}
@contentType = application/json

GET https://{{host}}/author HTTP/1.1

###

POST https://{{host}}/author HTTP/1.1
Content-Type: {{contentType}}

{
    "Username": "edward.kitchen"    
}

###

GET http://{{host}}/odata/author?$select=Username&filter='AuthorId gt 1' 

###

GET http://{{host}}/odata/author(6)?$select=Username

###

GET http://{{host}}/odata/author?$select=Username,AuthorId&filter=AuthorId gt 1&orderby=AuthorId desc